# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('kdr', models.NullBooleanField(default=False)),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('breakfast', models.NullBooleanField(default=False)),
                ('brunch', models.NullBooleanField(default=False)),
                ('dinner', models.NullBooleanField(default=False)),
                ('supper', models.NullBooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(0, 'Grupa 1'), (1, 'Grupa 2'), (2, 'Grupa 3'), (3, 'Grupa 4')])),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(0, 'śniadanie'), (1, 'drugie śniadanie'), (2, 'obiad'), (3, 'podwieczorek')])),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('child', models.ManyToManyField(to='management.Child')),
            ],
        ),
        migrations.CreateModel(
            name='PresenceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('present', models.NullBooleanField()),
                ('additional_hour', models.IntegerField(choices=[(0, '6:30'), (1, '12:00'), (2, '13:00'), (3, '14:00'), (4, '15:00'), (5, '16:00')], null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Child')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Group')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='presence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.PresenceList'),
        ),
        migrations.AddField(
            model_name='child',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Group'),
        ),
    ]
