# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20171122_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='breakfast',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='brunch',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='dinner',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='supper',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='presencelist',
            name='present',
            field=models.NullBooleanField(default=False),
        ),
    ]
