# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20171122_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='presence',
        ),
        migrations.AddField(
            model_name='presencelist',
            name='meal',
            field=models.IntegerField(choices=[(0, 'śniadanie'), (1, 'drugie śniadanie'), (2, 'obiad'), (3, 'podwieczorek')], default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
