# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20171124_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presencelist',
            name='meal',
            field=models.IntegerField(choices=[(0, 'śniadanie'), (1, 'drugie śniadanie'), (2, 'obiad'), (3, 'podwieczorek')], null=True),
        ),
    ]
