# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20171124_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencelist',
            name='hours_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presencelist',
            name='meal_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presencelist',
            name='presence_breakfast',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='presencelist',
            name='presence_brunch',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='presencelist',
            name='presence_dinner',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='presencelist',
            name='presence_fifteen',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='presencelist',
            name='presence_fourteen',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='presencelist',
            name='presence_six',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='presencelist',
            name='presence_sixteen',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='presencelist',
            name='presence_supper',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='presencelist',
            name='presence_thirteen',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='presencelist',
            name='presence_twelve',
            field=models.NullBooleanField(default=True),
        ),
    ]
