# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20171130_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presencelist',
            name='hours_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='presencelist',
            name='meal_price',
            field=models.FloatField(default=0),
        ),
    ]
