# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20171130_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presencelist',
            name='presence_breakfast',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='presencelist',
            name='presence_brunch',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='presencelist',
            name='presence_dinner',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='presencelist',
            name='presence_fifteen',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='presencelist',
            name='presence_fourteen',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='presencelist',
            name='presence_six',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='presencelist',
            name='presence_sixteen',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='presencelist',
            name='presence_supper',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='presencelist',
            name='presence_thirteen',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='presencelist',
            name='presence_twelve',
            field=models.NullBooleanField(),
        ),
    ]
